# Generated by Django 5.2.5 on 2025-10-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_rental_approved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='rental_days',
            field=models.PositiveIntegerField(default=7),
        ),
    ]
