# Generated by Django 5.2.5 on 2025-10-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=6),
        ),
    ]
