# Generated by Django 5.2.5 on 2025-10-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game_price_per_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=6),
        ),
    ]
